cargo-features = ["resolver"]

[workspace]
members = [
	"faucet",
	"traits",
	"relaychain-info",
	"price-oracle",
	"transaction-multi-payment",
	"nft",
	"asset-registry",
	"collator-rewards",
]

resolver = "2"

[patch.crates-io]
# TODO: https://github.com/paritytech/substrate/pull/11707
syn = { git = "https://github.com/dtolnay/syn", rev = "19b3f0b53525ac7ab0882882a822adbd874dbe8c" }
