cargo-features = ["resolver"]

[workspace]
members = [
	"faucet",
	"traits",
	"relaychain-info",
	"price-oracle",
	"transaction-multi-payment",
	"nft",
	"asset-registry",
	"collator-rewards",
  "liquidity-mining",
]

resolver = "2"
