cargo-features = ["resolver"]

[workspace]
members = [
	"faucet",
	"traits",
	"relaychain-info",
	"price-oracle",
	"route-executor",
	"transaction-multi-payment",
	"nft",
	"asset-registry",
	"adapters",
	"collator-rewards",
	"transaction-pause",
	"ema-oracle",
	"currencies",
]

resolver = "2"
