cargo-features = ["resolver"]

[workspace]
members = [
	"faucet",
	"traits",
	"relaychain-info",
	"price-oracle",
	"transaction-multi-payment",
	"nft",
	"asset-registry",
	"adapters",
	"collator-rewards",
  "liquidity-mining",
]

resolver = "2"

# Use a fork of ORML until we are using a version that includes
# https://github.com/open-web3-stack/open-runtime-module-library/pull/754
[patch."https://github.com/open-web3-stack/open-runtime-module-library"]
orml-currencies = { git = "https://github.com/apopiak/open-runtime-module-library", branch = "apopiak/on-new-account-9-17" }
orml-tokens = { git = "https://github.com/apopiak/open-runtime-module-library", branch = "apopiak/on-new-account-9-17" }
orml-traits = { git = "https://github.com/apopiak/open-runtime-module-library", branch = "apopiak/on-new-account-9-17" }
orml-utilities = { git = "https://github.com/apopiak/open-runtime-module-library", branch = "apopiak/on-new-account-9-17" }
