[package]
name = "pallet-transaction-multi-payment"
version = "8.0.4"
description = "Transaction multi currency payment support module"
authors = ["GalacticCoucil"]
edition = "2021"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/warehouse"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec.workspace = true
scale-info.workspace = true

# ORML dependencies
orml-traits.workspace = true

# HydraDX traits
hydradx-traits = { path = "../traits", default-features = false }

# Substrate dependencies
frame-support.workspace = true
frame-system.workspace = true
sp-api.workspace = true
sp-core.workspace = true
sp-std.workspace = true
sp-runtime.workspace = true
pallet-transaction-payment.workspace = true

[dev-dependencies]
pallet-currencies = { path = "../currencies", default-features = false }
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.29", default-features = false, features=["std"]}
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false, features=["std"] }
sp-io.workspace = true
test-utils = { path = "../test-utils", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-core/std",
    "sp-api/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "orml-traits/std",
    "hydradx-traits/std",
    "scale-info/std",
]
try-runtime = ["frame-support/try-runtime"]
